apiVersion: v1
kind: Secret
metadata:
  name: brigade-{{ sha256sum .Values.project| trunc 54 }}
  labels:
    app: brigade
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    component: project
  annotations:
    projectName: {{ .Values.project | quote }}
type: "brigade.sh/project"
stringData:
  repository: {{ .Values.repository }}
  sharedSecret: {{ .Values.sharedSecret }}
  cloneURL: {{ .Values.cloneURL }}
  initGitSubmodules: {{ default "false" .Values.initGitSubmodules }}
  {{ if .Values.defaultScript }}
  defaultScript: |
{{.Values.defaultScript | indent 4}}
  {{- end }}
  {{ if eq "NONE" .Values.vcsSidecar -}}
  {{- else if empty .Values.vcsSidecar -}}
  vcsSidecar: {{ printf "deis/git-sidecar:%s" .Chart.Version }}
  {{- else }}
  vcsSidecar: {{ .Values.vcsSidecar }}
  {{- end }}
  {{ if .Values.buildStorageSize }}
  buildStorageSize: {{ .Values.buildStorageSize }}
  {{- end }}
  {{ if .Values.secrets }}
  secrets: '{{ .Values.secrets | toJson }}'
  {{- end }}
  {{ range $k, $v := .Values.github}}
  github.{{ $k }}: {{ $v }}
  {{- end }}
  {{ range $k, $v := .Values.kubernetes }}
  kubernetes.{{ $k }}: {{ $v }}
  {{- end }}
  {{ if .Values.sshKey }}
  sshKey: {{.Values.sshKey | replace "\n" "$" }}
  {{- end }}
  allowPrivilegedJobs: {{ default "true" .Values.allowPrivilegedJobs }}
  {{ if .Values.allowHostMounts -}}
  allowHostMounts: {{ .Values.allowHostMounts }}
  {{ else }}
  allowHostMounts: {{ "false" }}
  {{- end }}
  {{ range $k, $v := .Values.worker -}}
  worker.{{ $k }}: {{ $v }}
  {{ end -}}
  {{if .Values.workerCommand -}}
  workerCommand: {{.Values.workerCommand }}
  {{- end }}
