apiVersion: v1
kind: Secret
metadata:
  name: acid-{{ sha256sum .Values.project| trunc 54 }}
  labels:
    managedBy: acid
    release: {{ .Release.Name | quote }}
  annotations:
    projectName: {{ .Values.project | quote }}
type: Opaque
data:
  repository: {{ .Values.repository | b64enc }}
  secret: {{ .Values.secret | b64enc }}
  {{ if .Values.githubToken -}} githubToken: {{.Values.githubToken | b64enc }}{{- end }}
  {{ if .Values.sshKey -}} sshKey: {{.Values.sshKey | replace "\n" "$" | b64enc }}{{- end }}
