apiVersion: v1
kind: Service
metadata:
  name: {{ template "acid.fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "acid.fullname" . }}-api
