{{ $fname := include "acid.worker.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acid-worker
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "acid.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets", "persistentVolumeClaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: {{ template "acid.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: acid-worker
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
