apiVersion: v1
kind: Secret
metadata:
  name: acid-{{ sha256sum .Values.project| trunc 54 }}
  labels:
    app: acid
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    component: project
  annotations:
    projectName: {{ .Values.project | quote }}
type: Opaque
data:
  repository: {{ .Values.repository | b64enc }}
  sharedSecret: {{ .Values.sharedSecret | b64enc }}
  cloneURL: {{ .Values.cloneURL | b64enc }}
  vcsSidecar: {{ .Values.vcsSidecar | default "acidic.azurecr.io/git-sidecar:latest" | b64enc }}
  secrets: {{ .Values.secrets | toJson | b64enc }}
  {{ if .Values.github.token -}}
  github.token: {{.Values.github.token | b64enc }}
  {{- end }}
  {{ if .Values.sshKey -}}
  sshKey: {{.Values.sshKey | replace "\n" "$" | b64enc }}
  {{- end }}
