{{ if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "brigade.api.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "brigade.api.fullname" . }}
{{ end }}
